package edu.web.news.controller.command;

public enum CommandName {

	DO_AUTH, DO_REGISTRATION,

	GO_TO_START_PAGE, GO_TO_AUTHENTICATION_PAGE, GO_TO_REGISTRATION_PAGE, GO_TO_ADMIN_PAGE,

	ADD_NEWS, DELETE_NEWS, UPDATE_NEWS, DISPLAY_ALL_NEWS,
	


	NO_SUCH_COMMAND
}
